import { PageHero } from "../components/ContentLayout";
import { EnquiryForm } from "../components/MockForms";

const offices = [
  { name: "Head Office USA", flags: ["us"], phone: "+1 828 691 91580", address: "658 E Sunset Dr, Hendersonville" },
  { name: "Singapore & Malaysia Office", flags: ["sg", "my"], phone: "+60 16 666 4486", email: "dkumar@aacihealthcare.com" },
  { name: "Vietnam Office", flags: ["vn"], phone: "+84 909 228 476", email: "pble@aacihealthcare.com" },
  { name: "Bangladesh Office", flags: ["bd"], phone: "+88 171 301 9190", email: "mzkarim@aacihealthcare.com" },
  { name: "South Korea Office", flags: ["kr"], phone: "+82 10 8345 1991", email: "yk@imdr.kr" },
  { name: "Myanmar Office", flags: ["mm"], phone: "+95 969 511 5533", email: "drnilarhan@gmail.com" },
  { name: "China & Taiwan Office", flags: ["cn", "tw"], phone: "+86 139 1655 4749", email: "corejudos@auroramri.com" },
];

export default function ContactPage(){return <><PageHero eyebrow="CONTACT AACI" title="Let’s advance quality together." intro="Connect with AACI Asia Pacific for accreditation, certification, education and quality-improvement support."/><section className="page-content contact-page"><div className="container"><section className="contact-page__primary"><div className="contact-page__image"><img src="/aaci-office.webp" alt="AACI Asia Pacific office"/></div><div className="contact-page__details"><p className="eyebrow">AACI ASIA PACIFIC</p><h2>Your regional partner for safer care.</h2><p>AACI is an internationally recognised accreditation, certification and advisory organisation dedicated to advancing healthcare quality, patient safety and service excellence.</p><div className="contact-page__contact-person"><span>CONTACT PERSON</span><strong>Somporn Kumphong, MD</strong><b>SVP & CEO, Asia Pacific</b></div><div className="contact-page__channels"><a href="tel:+66898995436"><small>CALL US</small>+66 89 899 5436</a><a href="mailto:somporn.kumphong@aacihealthcare.com"><small>EMAIL</small>somporn.kumphong@aacihealthcare.com</a></div><address>9/25 Soi Sukhonthasawat 25, Sukhonthasawat Road,<br/>Ladprao, Bangkok 10230, Thailand</address></div></section><section className="contact-page__network"><header><p className="eyebrow">OUR REGIONAL NETWORK</p><h2>Local support across Asia Pacific.</h2></header><div className="contact-page__offices">{offices.map((office)=><article key={office.name}><h3><span className="office-flags">{office.flags.map((flag)=><img key={flag} src={`https://flagcdn.com/w80/${flag}.png`} alt=""/>)}</span>{office.name}</h3><a href={`tel:${office.phone.replace(/\s/g,"")}`}>T: {office.phone}</a>{office.email ? <a href={`mailto:${office.email}`}>E: {office.email}</a> : <p>{office.address}</p>}</article>)}</div></section><section className="contact-page__form"><header><p className="eyebrow">SEND AN ENQUIRY</p><h2>How can we help?</h2><p>Tell us what you need. Our Asia Pacific team will respond with the right next step for your organisation.</p></header><EnquiryForm kind="contact"/></section></div></section></>}
