"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, BadgeDollarSign, CalendarDays, Clock3, Gift, GraduationCap, Mail, Monitor, Phone, Users } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { getSupabaseBrowserClient } from "../../lib/supabase/client";
import { CourseRecord, REGISTRATION_STATUS_LABELS, formatCourseFee, formatSessionDate, getCourseImageUrl } from "../../lib/courses";

const COURSE_SELECT = "id, slug, title, category, summary, description, cover_image_path, duration_text, format_text, fee_amount, fee_currency, registration_url, status, published_at, sort_order, is_featured, accent_color, topics, early_bird_deadline, early_bird_discount_percent, created_at, updated_at, course_sessions(id, course_id, starts_at, ends_at, timezone, capacity, registration_deadline, registration_url, registration_status, status, sort_order, created_at, updated_at)";
const PUBLIC_SITE_ORIGIN = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ?? "";

function RegistrationLink({ url, label }: { url: string | null; label: string }) {
  if (!url) return <Link className="text-link" href="/accreditation/request">{label} <b>→</b></Link>;
  if (url.startsWith("/")) return <Link className="text-link" href={url}>{label} <b>→</b></Link>;
  return <a className="text-link" href={url} target="_blank" rel="noreferrer">{label} <b>→</b></a>;
}

function scheduleText(course: CourseRecord) {
  if (course.duration_text) return course.duration_text;
  const sessions = course.course_sessions ?? [];
  if (!sessions.length) return "Schedule to be announced";
  if (sessions.length === 1) return formatSessionDate(sessions[0].starts_at, sessions[0].timezone);
  return `${formatSessionDate(sessions[0].starts_at, sessions[0].timezone)} · ${sessions.length} sessions`;
}

function sessionTime(course: CourseRecord) {
  const session = course.course_sessions?.[0];
  if (!session) return "See schedule";
  const format = (value: string) => new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit", hour12: true, timeZone: session.timezone }).format(new Date(value));
  return session.ends_at ? `${format(session.starts_at)} – ${format(session.ends_at)}` : format(session.starts_at);
}

function CourseRegistrationPanel({ course, capacity, registrationUrl, origin, titleId }: { course: CourseRecord; capacity: number; registrationUrl: string | null; origin: string; titleId: string }) {
  const discount = course.early_bird_discount_percent ?? 20;
  const registrationTarget = registrationUrl ?? "/accreditation/request";
  const registrationQrValue = registrationTarget.startsWith("http") || !origin ? registrationTarget : `${origin}${registrationTarget}`;
  return <section className="container course-registration-panel" aria-labelledby={titleId}><div className="course-registration-panel__promos"><article className="course-registration-promo course-registration-promo--seats"><Users size={42} strokeWidth={1.7} /><div><p>LIMITED SEATS</p><h2 id={titleId}>Only {capacity} participants</h2><span>per class · First come, first served</span></div></article><article className="course-registration-promo course-registration-promo--early"><Gift size={42} strokeWidth={1.7} /><div><p>EARLY BIRD PROMOTION</p><h2>{discount}% OFF</h2><span>{course.early_bird_deadline ? `Register by ${new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${course.early_bird_deadline}T00:00:00Z`))}` : "Register at least 30 days before class"}</span></div></article><article className="course-registration-promo course-registration-promo--scan"><div><p>SCAN TO REGISTER</p><RegistrationLink url={registrationUrl} label="Register online" /></div><a href={registrationTarget} aria-label={`Register for ${course.title}`} target={registrationTarget.startsWith("http") ? "_blank" : undefined} rel={registrationTarget.startsWith("http") ? "noreferrer" : undefined}><QRCodeSVG value={registrationQrValue} size={104} level="M" bgColor="#ffffff" fgColor="#071f37" /></a></article></div><div className="course-registration-contact"><header><p className="eyebrow">CONTACT INFORMATION</p><h2>We’re here to help you register.</h2></header><div><article><Users size={24} /><p><strong>Mr. Nirachit Rerngsangvatana</strong><span>AACI Asia Pacific Office</span></p></article><a href="tel:+66852296651"><Phone size={24} /><p><strong>Mobile / WhatsApp</strong><span>+66 85 229 6651</span></p></a><a href="mailto:nirachit.rerngsangvatana@aacihealthcare.com"><Mail size={24} /><p><strong>Email</strong><span>nirachit.rerngsangvatana@aacihealthcare.com</span></p></a></div></div></section>;
}

export default function PublicCourseDirectory() {
  const [courses, setCourses] = useState<CourseRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => { const legacySlug = window.location.hash.slice(1); if (/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(legacySlug)) { window.location.replace(`/services/courses/${legacySlug}`); return; } let active = true; getSupabaseBrowserClient().from("courses").select(COURSE_SELECT).eq("status", "published").order("sort_order", { ascending: true }).then(({ data, error: queryError }) => { if (!active) return; setCourses(((data ?? []) as unknown as CourseRecord[]).map((item) => ({ ...item, course_sessions: (item.course_sessions ?? []).filter((session) => session.status === "published").sort((a, b) => a.sort_order - b.sort_order || a.starts_at.localeCompare(b.starts_at)) }))); setError(Boolean(queryError)); setLoading(false); }); return () => { active = false; }; }, []);
  const featuredCourse = courses.find((course) => course.is_featured) ?? courses[0];
  const featuredSession = featuredCourse?.course_sessions?.find((session) => session.registration_status === "open") ?? featuredCourse?.course_sessions?.[0];
  const featuredRegistrationUrl = featuredSession?.registration_url ?? featuredCourse?.registration_url ?? null;
  return <><section className="academy-programmes container"><header><p className="eyebrow">2026 EDUCATION PROGRAMMES</p><h2>Choose a programme that fits your next step.</h2><p>Explore AACI professional education, live class schedules and registration options.</p></header>{loading ? <div className="people-public-state" role="status">Loading courses…</div> : error ? <div className="people-public-state people-public-state--error" role="alert">We could not load the courses. Please try again shortly.</div> : courses.length === 0 ? <div className="people-public-state"><GraduationCap size={34} strokeWidth={1.5} /><h2>New courses are on their way.</h2><p>Contact our team for current professional education opportunities.</p></div> : <div className="academy-programmes__grid">{courses.map((course) => {
    const image = getCourseImageUrl(course.cover_image_path); const featured = course.is_featured; const fee = formatCourseFee(course.fee_amount, course.fee_currency);
    return <article id={course.slug} key={course.id} className={featured ? "academy-programmes__featured" : undefined} style={{ "--programme-color": course.accent_color } as React.CSSProperties}><Link className="academy-programmes__image" href={`/services/courses/${course.slug}`}>{image ? <img src={image} alt={course.title} /> : <span className="academy-programmes__placeholder"><GraduationCap size={52} strokeWidth={1.3} /></span>}<div className="academy-programmes__tag">{featured ? "Registration is now open" : course.category ?? "AACI Course"}</div></Link><div className="academy-programmes__body">{featured && <p className="academy-programmes__featured-label">{course.category ?? "AACI PROFESSIONAL TRAINING"}</p>}<h3><Link className="academy-programmes__title-link" href={`/services/courses/${course.slug}`}>{course.title}</Link></h3>{course.summary && <p className={featured ? "academy-programmes__featured-summary" : "academy-programmes__summary"}>{course.summary}</p>}{featured && course.early_bird_discount_percent && <div className="academy-programmes__promotion"><strong>{course.early_bird_discount_percent}% OFF</strong><span>{course.early_bird_deadline ? `Early bird registration by ${new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${course.early_bird_deadline}T00:00:00Z`))}` : "Early bird offer available"}</span></div>}<p className="academy-programmes__dates">{scheduleText(course)}</p><dl><div><dt>Time</dt><dd>{sessionTime(course)}</dd></div><div><dt>Format</dt><dd>{course.format_text ?? "To be announced"}</dd></div><div><dt>Fee</dt><dd>{fee}</dd></div></dl>{featured && course.topics.length > 0 && <div className="academy-programmes__topics" aria-label="Course topics">{course.topics.map((topic) => <span key={topic}>{topic}</span>)}</div>}<Link className="text-link" href={`/services/courses/${course.slug}`}>View course <b>→</b></Link></div></article>;
  })}</div>}</section><section className="academy-audience"><div className="container"><p className="eyebrow">WHO WE SERVE</p><div>{["Healthcare professionals", "Hospital leaders", "Quality & safety practitioners", "Students & academics", "Global healthcare community"].map((item, index)=><article key={item}><span>0{index + 1}</span><strong>{item}</strong></article>)}</div></div></section>{featuredCourse && <CourseRegistrationPanel course={featuredCourse} capacity={featuredSession?.capacity ?? 50} registrationUrl={featuredRegistrationUrl} origin={PUBLIC_SITE_ORIGIN} titleId="course-directory-registration-title" />}</>;
}

function CourseDescription({ description }: { description: string }) {
  const blocks = description.split(/\n\s*\n/).map((block) => block.trim()).filter(Boolean);
  return <>{blocks.map((block, index) => { const heading = (index === 0 && /open/i.test(block)) || (/^[A-Z0-9][A-Z0-9 ?/&•–—-]+$/.test(block) && block.length < 80); if (heading) return <h2 key={index}>{block}</h2>; const lines = block.split("\n"); return <p key={index}>{lines.map((line, lineIndex) => <span key={lineIndex}>{line}{lineIndex < lines.length - 1 && <br />}</span>)}</p>; })}</>;
}

export function PublicCourseDetail({ slug }: { slug: string }) {
  const [course, setCourse] = useState<CourseRecord | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => { let active = true; getSupabaseBrowserClient().from("courses").select(COURSE_SELECT).eq("slug", slug).eq("status", "published").maybeSingle().then(({ data, error: queryError }) => { if (!active) return; const item = data as unknown as CourseRecord | null; setCourse(item ? { ...item, course_sessions: (item.course_sessions ?? []).filter((session) => session.status === "published").sort((a, b) => a.sort_order - b.sort_order || a.starts_at.localeCompare(b.starts_at)) } : null); setError(Boolean(queryError)); setLoading(false); }); return () => { active = false; }; }, [slug]);
  if (loading) return <main className="course-detail-page"><div className="container people-public-state" role="status">Loading course…</div></main>;
  if (error || !course) return <main className="course-detail-page"><div className="container people-public-state people-public-state--error" role="alert"><GraduationCap size={34} strokeWidth={1.5} /><h1>Course unavailable</h1><p>This course is unavailable or has not been published.</p><Link className="text-link" href="/services/courses">View all courses <b>→</b></Link></div></main>;
  const image = getCourseImageUrl(course.cover_image_path); const sessions = course.course_sessions ?? []; const registrationOpen = !sessions.length || sessions.some((session) => session.registration_status === "open");
  const capacity = sessions.find((session) => session.capacity)?.capacity ?? 50;
  const registrationUrl = sessions.find((session) => session.registration_status === "open" && session.registration_url)?.registration_url ?? course.registration_url;
  return <main className="course-detail-page"><section className="course-detail-hero"><div className="container"><Link href="/services/courses"><ArrowLeft size={16} /> All courses</Link><p className="eyebrow light">{course.category ?? "AACI ACADEMY"}</p><h1>{course.title}</h1><p>{course.summary}</p></div></section><div className="container course-detail-layout"><article className="course-detail-content">{image && <img className="course-detail-cover" src={image} alt={course.title} />}<div className="course-detail-copy"><CourseDescription description={course.description} />{course.topics.length > 0 && <section className="course-detail-topics"><p className="eyebrow">WHO SHOULD ATTEND?</p><h2>Build the competencies that matter.</h2><ul>{course.topics.map((topic) => <li key={topic}>{topic}</li>)}</ul></section>}{sessions.length > 0 && <section className="course-detail-sessions"><p className="eyebrow">CLASS SCHEDULE</p><h2>{sessions.length} live training sessions</h2><div>{sessions.map((session, index) => <article key={session.id}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{formatSessionDate(session.starts_at, session.timezone)}</strong>{session.ends_at && <small>Ends {formatSessionDate(session.ends_at, session.timezone)}</small>}</div><em>{REGISTRATION_STATUS_LABELS[session.registration_status]}</em></article>)}</div></section>}</div></article><aside className="course-detail-sidebar"><section><p className="eyebrow">COURSE DETAILS</p><h2>Plan your training</h2><dl><div><dt><CalendarDays size={17} />Training period</dt><dd>{scheduleText(course)}</dd></div><div><dt><Clock3 size={17} />Time</dt><dd>{sessionTime(course)}<small>Bangkok Time (GMT+7)</small></dd></div><div><dt><Monitor size={17} />Format</dt><dd>{course.format_text ?? "To be announced"}</dd></div><div><dt><BadgeDollarSign size={17} />Registration fee</dt><dd>{formatCourseFee(course.fee_amount, course.fee_currency)}</dd></div></dl>{course.early_bird_discount_percent && <div className="course-detail-earlybird"><strong>{course.early_bird_discount_percent}% OFF</strong><span>{course.early_bird_deadline ? `Register by ${new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${course.early_bird_deadline}T00:00:00Z`))}` : "Early bird offer"}</span></div>}{registrationOpen ? <RegistrationLink url={registrationUrl} label="Register now" /> : <p className="course-detail-closed">Registration is currently closed.</p>}</section></aside></div><CourseRegistrationPanel course={course} capacity={capacity} registrationUrl={registrationUrl} origin={PUBLIC_SITE_ORIGIN} titleId="course-registration-title" /></main>;
}
