"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarDays, Clock3, Eye, GraduationCap, ImagePlus, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { getSupabaseBrowserClient } from "../../../lib/supabase/client";
import { useAdminPermissions } from "../../../lib/admin-access";
import { COURSE_STATUS_LABELS, CourseRecord, CourseSessionRecord, CourseStatus, REGISTRATION_STATUS_LABELS, RegistrationStatus, formatCourseFee, formatSessionDate, getCourseImageUrl, slugifyCourseTitle } from "../../../lib/courses";
import { AdminRole } from "../../../lib/news";
import AdminSidebar from "../AdminSidebar";

type CourseFilter = "all" | CourseStatus;
type CourseForm = { title: string; slug: string; category: string; summary: string; description: string; duration_text: string; format_text: string; fee_amount: string; fee_currency: string; registration_url: string; status: CourseStatus; published_at: string; sort_order: string; is_featured: boolean; accent_color: string; topics: string; early_bird_deadline: string; early_bird_discount_percent: string };
type SessionForm = { id?: string; starts_at: string; ends_at: string; timezone: string; capacity: string; registration_deadline: string; registration_url: string; registration_status: RegistrationStatus; status: CourseStatus; sort_order: string };
const COURSE_SELECT = "id, slug, title, category, summary, description, cover_image_path, duration_text, format_text, fee_amount, fee_currency, registration_url, status, published_at, sort_order, is_featured, accent_color, topics, early_bird_deadline, early_bird_discount_percent, created_at, updated_at, course_sessions(id, course_id, starts_at, ends_at, timezone, capacity, registration_deadline, registration_url, registration_status, status, sort_order, created_at, updated_at)";
const FILTERS: Array<{ value: CourseFilter; label: string }> = [{ value: "all", label: "All courses" }, { value: "draft", label: "Draft" }, { value: "published", label: "Published" }, { value: "archived", label: "Archived" }];
const TIMEZONES = ["Asia/Bangkok", "Asia/Singapore", "Asia/Ho_Chi_Minh", "Asia/Yangon", "Asia/Dhaka", "Asia/Kuala_Lumpur", "UTC"];
const emptyForm = (): CourseForm => ({ title: "", slug: "", category: "", summary: "", description: "", duration_text: "", format_text: "Live online training", fee_amount: "", fee_currency: "USD", registration_url: "", status: "draft", published_at: "", sort_order: "1", is_featured: false, accent_color: "#173d69", topics: "", early_bird_deadline: "", early_bird_discount_percent: "" });
const emptySession = (order: number): SessionForm => ({ starts_at: "", ends_at: "", timezone: "Asia/Bangkok", capacity: "", registration_deadline: "", registration_url: "", registration_status: "open", status: "draft", sort_order: String(order) });
const optional = (value: string) => value.trim() || null;
const safeFilename = (filename: string) => filename.toLowerCase().replace(/[^a-z0-9.]+/g, "-").replace(/^-+|-+$/g, "") || "course-cover";
function toLocal(value: string | null) { if (!value) return ""; const date = new Date(value); if (Number.isNaN(date.getTime())) return ""; return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function sessionToForm(item: CourseSessionRecord): SessionForm { return { id: item.id, starts_at: toLocal(item.starts_at), ends_at: toLocal(item.ends_at), timezone: item.timezone, capacity: item.capacity === null ? "" : String(item.capacity), registration_deadline: toLocal(item.registration_deadline), registration_url: item.registration_url ?? "", registration_status: item.registration_status, status: item.status, sort_order: String(item.sort_order) }; }

export default function AdminCoursesPage() {
  const { can } = useAdminPermissions();
  const [role, setRole] = useState<AdminRole | null>(null); const [userLabel, setUserLabel] = useState("Administrator");
  const [courses, setCourses] = useState<CourseRecord[]>([]); const [filter, setFilter] = useState<CourseFilter>("all"); const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [notice, setNotice] = useState("");
  const [editing, setEditing] = useState<CourseRecord | null>(null); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState<CourseForm>(emptyForm()); const [sessions, setSessions] = useState<SessionForm[]>([]); const [removedSessionIds, setRemovedSessionIds] = useState<string[]>([]); const [slugTouched, setSlugTouched] = useState(false);
  const [coverFile, setCoverFile] = useState<File | null>(null); const [coverPreview, setCoverPreview] = useState<string | null>(null); const [formError, setFormError] = useState(""); const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState<CourseRecord | null>(null); const [deleteBusy, setDeleteBusy] = useState(false);

  async function loadCourses() { setLoadError(""); const { data, error } = await getSupabaseBrowserClient().from("courses").select(COURSE_SELECT).order("sort_order", { ascending: true }); if (error) { setCourses([]); setLoadError("We could not load the courses. Run the latest Supabase migration, then refresh this page."); return; } setCourses(((data ?? []) as unknown as CourseRecord[]).map((item) => ({ ...item, course_sessions: [...(item.course_sessions ?? [])].sort((a, b) => a.sort_order - b.sort_order || a.starts_at.localeCompare(b.starts_at)) }))); }
  useEffect(() => { let active = true; (async () => { const supabase = getSupabaseBrowserClient(); const { data } = await supabase.auth.getUser(); if (!active) return; if (!data.user) { window.location.replace("/admin"); return; } const { data: profile } = await supabase.from("admin_profiles").select("email, display_name, role").eq("id", data.user.id).eq("is_active", true).maybeSingle(); if (!active) return; if (!profile) { await supabase.auth.signOut(); window.location.replace("/admin"); return; } setRole(profile.role as AdminRole); setUserLabel(profile.display_name ?? profile.email); await loadCourses(); if (active) setLoading(false); })(); return () => { active = false; }; }, []);
  useEffect(() => () => { if (coverPreview?.startsWith("blob:")) URL.revokeObjectURL(coverPreview); }, [coverPreview]);

  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return courses.filter((item) => (filter === "all" || item.status === filter) && (!term || `${item.title} ${item.category ?? ""} ${item.summary}`.toLowerCase().includes(term))); }, [courses, filter, search]);
  function count(value: CourseFilter) { return value === "all" ? courses.length : courses.filter((item) => item.status === value).length; }
  function openCreate() { setEditing(null); setForm({ ...emptyForm(), sort_order: String(courses.length + 1) }); setSessions([]); setRemovedSessionIds([]); setSlugTouched(false); setCoverFile(null); setCoverPreview(null); setFormError(""); setFormOpen(true); }
  function openEdit(item: CourseRecord) { setEditing(item); setForm({ title: item.title, slug: item.slug, category: item.category ?? "", summary: item.summary, description: item.description, duration_text: item.duration_text ?? "", format_text: item.format_text ?? "", fee_amount: item.fee_amount === null ? "" : String(item.fee_amount), fee_currency: item.fee_currency, registration_url: item.registration_url ?? "", status: item.status, published_at: toLocal(item.published_at), sort_order: String(item.sort_order), is_featured: item.is_featured, accent_color: item.accent_color, topics: item.topics.join(", "), early_bird_deadline: item.early_bird_deadline ?? "", early_bird_discount_percent: item.early_bird_discount_percent === null ? "" : String(item.early_bird_discount_percent) }); setSessions((item.course_sessions ?? []).map(sessionToForm)); setRemovedSessionIds([]); setSlugTouched(true); setCoverFile(null); setCoverPreview(getCourseImageUrl(item.cover_image_path)); setFormError(""); setFormOpen(true); }
  function closeForm(force = false) { if (saving && !force) return; setFormOpen(false); setEditing(null); setCoverFile(null); setCoverPreview(null); setSessions([]); setRemovedSessionIds([]); setFormError(""); }
  function handleCover(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) { setFormError("Cover image must be a JPEG, PNG or WebP file."); event.target.value = ""; return; } if (file.size > 10 * 1024 * 1024) { setFormError("Cover image must be no larger than 10 MB."); event.target.value = ""; return; } if (coverPreview?.startsWith("blob:")) URL.revokeObjectURL(coverPreview); setCoverFile(file); setCoverPreview(URL.createObjectURL(file)); setFormError(""); }
  function updateSession(index: number, values: Partial<SessionForm>) { setSessions((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, ...values } : item)); }
  function removeSession(index: number) { const item = sessions[index]; if (item.id && !can("courses.delete")) return; if (item.id) setRemovedSessionIds((ids) => [...ids, item.id!]); setSessions((items) => items.filter((_, itemIndex) => itemIndex !== index)); }
  async function removeCover(path: string | null) { if (!path || path.startsWith("/") || /^https?:\/\//i.test(path)) return null; const { error } = await getSupabaseBrowserClient().storage.from("cms-images").remove([path]); return error; }

  async function submitCourse(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setFormError("");
    if (!form.title.trim() || !form.slug.trim() || !form.summary.trim()) { setFormError("Title, URL slug and summary are required."); setSaving(false); return; }
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(form.slug)) { setFormError("URL slug may contain lowercase letters, numbers and hyphens only."); setSaving(false); return; }
    if (sessions.some((item) => !item.starts_at || (item.ends_at && new Date(item.ends_at) < new Date(item.starts_at)))) { setFormError("Every class session needs a valid start time, and its end must be after its start."); setSaving(false); return; }
    const supabase = getSupabaseBrowserClient(); const { data: auth } = await supabase.auth.getUser(); const userId = auth.user?.id; if (!userId) { window.location.replace("/admin"); return; }
    const courseId = editing?.id ?? crypto.randomUUID(); let coverPath = editing?.cover_image_path ?? null; let uploadedPath: string | null = null;
    if (coverFile) { uploadedPath = `courses/${courseId}/${Date.now()}-${safeFilename(coverFile.name)}`; const { error } = await supabase.storage.from("cms-images").upload(uploadedPath, coverFile, { contentType: coverFile.type, upsert: false }); if (error) { setFormError(`Cover upload failed: ${error.message}`); setSaving(false); return; } coverPath = uploadedPath; }
    const status = form.status; const values = { slug: form.slug.trim(), title: form.title.trim(), category: optional(form.category), summary: form.summary.trim(), description: form.description.trim(), cover_image_path: coverPath, duration_text: optional(form.duration_text), format_text: optional(form.format_text), fee_amount: form.fee_amount ? Number(form.fee_amount) : null, fee_currency: form.fee_currency.trim().toUpperCase(), registration_url: optional(form.registration_url), status, published_at: status === "published" ? (form.published_at ? new Date(form.published_at).toISOString() : editing?.published_at ?? new Date().toISOString()) : (form.published_at ? new Date(form.published_at).toISOString() : null), sort_order: Math.max(0, Number(form.sort_order) || 0), is_featured: form.is_featured, accent_color: form.accent_color, topics: form.topics.split(",").map((item) => item.trim()).filter(Boolean), early_bird_deadline: optional(form.early_bird_deadline), early_bird_discount_percent: form.early_bird_discount_percent ? Number(form.early_bird_discount_percent) : null, updated_by: userId };
    const result = editing ? await supabase.from("courses").update(values).eq("id", courseId) : await supabase.from("courses").insert({ id: courseId, ...values, created_by: userId });
    if (result.error) { if (uploadedPath) await removeCover(uploadedPath); setFormError(`Course could not be saved: ${result.error.code === "23505" ? "This URL slug is already in use." : result.error.message}`); setSaving(false); return; }
    if (removedSessionIds.length && can("courses.delete")) { const { error } = await supabase.from("course_sessions").delete().in("id", removedSessionIds); if (error) { setFormError(`The course was saved, but removed sessions could not be deleted: ${error.message}`); setSaving(false); return; } }
    for (let index = 0; index < sessions.length; index += 1) { const item = sessions[index]; const sessionValues = { starts_at: new Date(item.starts_at).toISOString(), ends_at: item.ends_at ? new Date(item.ends_at).toISOString() : null, timezone: item.timezone, capacity: item.capacity ? Number(item.capacity) : null, registration_deadline: item.registration_deadline ? new Date(item.registration_deadline).toISOString() : null, registration_url: optional(item.registration_url), registration_status: item.registration_status, status: item.status, sort_order: Number(item.sort_order) || index + 1, updated_by: userId }; const sessionResult = item.id ? await supabase.from("course_sessions").update(sessionValues).eq("id", item.id) : await supabase.from("course_sessions").insert({ id: crypto.randomUUID(), course_id: courseId, ...sessionValues, created_by: userId }); if (sessionResult.error) { setFormError(`The course was saved, but a class session failed: ${sessionResult.error.message}`); setSaving(false); return; } }
    let cleanupFailed = false; if (can("courses.delete") && uploadedPath && editing?.cover_image_path && editing.cover_image_path !== uploadedPath) cleanupFailed = Boolean(await removeCover(editing.cover_image_path));
    await loadCourses(); closeForm(true); setNotice(`${form.title.trim()} was ${editing ? "updated" : "created"} successfully.${cleanupFailed ? " The previous cover could not be removed." : ""}`); setSaving(false);
  }

  async function confirmDelete() { if (!deleting || !can("courses.delete")) return; setDeleteBusy(true); const supabase = getSupabaseBrowserClient(); const { error } = await supabase.from("courses").delete().eq("id", deleting.id); if (error) { setLoadError(`Delete failed: ${error.message}`); setDeleteBusy(false); return; } const imageError = await removeCover(deleting.cover_image_path); setCourses((items) => items.filter((item) => item.id !== deleting.id)); setNotice(`${deleting.title} was deleted.${imageError ? " The cover could not be removed." : ""}`); setDeleting(null); setDeleteBusy(false); }
  async function signOut() { await getSupabaseBrowserClient().auth.signOut(); window.location.replace("/admin"); }
  if (loading || !role) return <main className="admin-dashboard admin-people"><div className="admin-loading" role="status">Checking access and loading courses…</div></main>;

  return <div className="admin-workspace"><AdminSidebar active="courses" userLabel={userLabel} role={role} onSignOut={signOut} /><main className="admin-dashboard admin-people admin-news admin-courses">
    <header className="admin-people__header"><div><Link className="admin-back" href="/admin"><ArrowLeft size={17} /> Administration</Link><p className="admin-kicker">AACI CONTENT MANAGEMENT</p><h1>Courses Management</h1><p>Manage course information, fees, registration and individual class sessions.</p></div>{can("courses.create") && <button className="button button-red admin-add-person" type="button" onClick={openCreate}><Plus size={18} /> Add course</button>}</header>
    <div className="admin-news__controls"><nav className="admin-people__tabs" aria-label="Course filters">{FILTERS.map((item) => <button key={item.value} type="button" aria-current={filter === item.value ? "page" : undefined} onClick={() => setFilter(item.value)}>{item.label}<span>{count(item.value)}</span></button>)}</nav><label className="admin-news__search"><Search size={17} /><span className="sr-only">Search courses</span><input type="search" placeholder="Search courses" value={search} onChange={(e) => setSearch(e.target.value)} /></label></div>
    {notice && <div className="admin-notice" role="status">{notice}<button type="button" aria-label="Dismiss notification" onClick={() => setNotice("")}><X size={16} /></button></div>}{loadError && <div className="admin-error admin-people__error" role="alert">{loadError}<button type="button" onClick={loadCourses}>Try again</button></div>}
    <section className="admin-people__list"><div className="admin-people__list-header"><div><h2>{FILTERS.find((item) => item.value === filter)?.label}</h2><p>{filtered.length} {filtered.length === 1 ? "course" : "courses"}</p></div><small>Only published courses appear on the public website.</small></div>{filtered.length === 0 ? <div className="admin-people__empty"><GraduationCap size={34} strokeWidth={1.5} /><h3>No courses found</h3><p>Create a course or try a different filter.</p>{can("courses.create") && <button className="button button-red" type="button" onClick={openCreate}><Plus size={17} /> Add course</button>}</div> : <div className="admin-news__rows">{filtered.map((item) => { const image = getCourseImageUrl(item.cover_image_path); const firstSession = item.course_sessions?.[0]; return <article className="admin-news-row admin-course-row" key={item.id}><div className="admin-news-row__image">{image ? <img src={image} alt="" /> : <GraduationCap size={25} strokeWidth={1.5} />}</div><div className="admin-news-row__identity"><p>{item.category ?? "Course"}{item.is_featured ? " · Featured" : ""}</p><h3>{item.title}</h3><small>{item.duration_text ?? (firstSession ? formatSessionDate(firstSession.starts_at, firstSession.timezone) : "Schedule to be announced")} · {formatCourseFee(item.fee_amount, item.fee_currency)} · {item.course_sessions?.length ?? 0} sessions</small></div><span className={`admin-status admin-status--${item.status}`}>{COURSE_STATUS_LABELS[item.status]}</span><div className="admin-person-row__actions">{item.status === "published" && <Link href={`/services/courses/${item.slug}`} target="_blank"><Eye size={16} /> View</Link>}{can("courses.update") && <button type="button" onClick={() => openEdit(item)}><Pencil size={16} /> Edit</button>}{can("courses.delete") && <button className="admin-person-row__delete" type="button" onClick={() => setDeleting(item)}><Trash2 size={16} /> Delete</button>}</div></article>; })}</div>}</section>
    {formOpen && <div className="admin-modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) closeForm(); }}><section className="admin-person-form admin-news-form admin-course-form" role="dialog" aria-modal="true" aria-labelledby="course-form-title"><header><div><p className="admin-kicker">{editing ? "EDIT COURSE" : "ADD COURSE"}</p><h2 id="course-form-title">{editing ? editing.title : "Create a course"}</h2></div><button type="button" onClick={() => closeForm()} aria-label="Close form"><X size={22} /></button></header><form onSubmit={submitCourse}>
      <fieldset><legend>Course details</legend><div className="admin-form-grid"><label className="admin-field admin-field--wide">Title <span>*</span><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value, slug: slugTouched ? form.slug : slugifyCourseTitle(e.target.value) })} required /></label><label className="admin-field">URL slug <span>*</span><input value={form.slug} onChange={(e) => { setSlugTouched(true); setForm({ ...form, slug: e.target.value }); }} required /></label><label className="admin-field">Category<input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="AACI Professional Training" /></label><label className="admin-field admin-field--wide">Summary <span>*</span><textarea rows={3} value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} required /></label><label className="admin-field admin-field--wide">Description<textarea className="admin-news-form__content" rows={7} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label className="admin-photo-field"><span>Course image</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={handleCover} /><span className="admin-photo-picker admin-news-photo-picker">{coverPreview ? <img src={coverPreview} alt="Course preview" /> : <ImagePlus size={25} />}<span><strong>{coverFile ? coverFile.name : "Choose an image"}</strong><small>JPEG, PNG or WebP · maximum 10 MB</small></span></span></label></div></fieldset>
      <fieldset><legend>Schedule, fee and registration</legend><div className="admin-form-grid"><label className="admin-field admin-field--wide">Schedule summary<input value={form.duration_text} onChange={(e) => setForm({ ...form, duration_text: e.target.value })} placeholder="17 September – 5 November 2026 · Every Thursday" /></label><label className="admin-field">Training format<input value={form.format_text} onChange={(e) => setForm({ ...form, format_text: e.target.value })} placeholder="Online training via Zoom" /></label><label className="admin-field">Registration fee<input type="number" min="0" step="0.01" value={form.fee_amount} onChange={(e) => setForm({ ...form, fee_amount: e.target.value })} /></label><label className="admin-field">Currency<input maxLength={3} value={form.fee_currency} onChange={(e) => setForm({ ...form, fee_currency: e.target.value })} /></label><label className="admin-field admin-field--wide">Registration link<input type="url" value={form.registration_url} onChange={(e) => setForm({ ...form, registration_url: e.target.value })} placeholder="https://example.com/register" /></label><label className="admin-field">Early-bird deadline<input type="date" value={form.early_bird_deadline} onChange={(e) => setForm({ ...form, early_bird_deadline: e.target.value })} /></label><label className="admin-field">Early-bird discount (%)<input type="number" min="1" max="100" value={form.early_bird_discount_percent} onChange={(e) => setForm({ ...form, early_bird_discount_percent: e.target.value })} /></label><label className="admin-field admin-field--wide">Topics<input value={form.topics} onChange={(e) => setForm({ ...form, topics: e.target.value })} placeholder="Patient Safety, Survey Methodology, Team Leadership" /><small>Separate topics with commas.</small></label></div></fieldset>
      <fieldset><legend>Display and publishing</legend><div className="admin-form-grid"><label className="admin-field">Sort order<input type="number" min="0" value={form.sort_order} onChange={(e) => setForm({ ...form, sort_order: e.target.value })} /></label><label className="admin-field">Accent colour<input type="color" value={form.accent_color} onChange={(e) => setForm({ ...form, accent_color: e.target.value })} /></label><label className="admin-field admin-field--wide"><span className="admin-event-all-day"><input type="checkbox" checked={form.is_featured} onChange={(e) => setForm({ ...form, is_featured: e.target.checked })} /> Featured course <small>Show as a large card above the standard course grid.</small></span></label><label className="admin-field">Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as CourseStatus })}><option value="draft">Draft</option><option value="published" disabled={!can("courses.publish")}>Published</option><option value="archived">Archived</option></select>{!can("courses.publish") && <small>A role with Publish permission must publish courses.</small>}</label><label className="admin-field">Publish date<div className="admin-news-date"><CalendarDays size={16} /><input type="datetime-local" value={form.published_at} onChange={(e) => setForm({ ...form, published_at: e.target.value })} /></div></label></div></fieldset>
      <fieldset><div className="admin-course-sessions__heading"><div><legend>Class sessions</legend><p>Add each live class date, time and registration status.</p></div><button type="button" onClick={() => setSessions((items) => [...items, emptySession(items.length + 1)])}><Plus size={16} /> Add session</button></div>{sessions.length === 0 ? <div className="admin-course-sessions__empty"><Clock3 size={22} /><span>No class sessions have been added.</span></div> : <div className="admin-course-sessions">{sessions.map((item, index) => <section key={item.id ?? `new-${index}`}><header><strong>Session {index + 1}</strong>{(!item.id || can("courses.delete")) && <button type="button" onClick={() => removeSession(index)}><Trash2 size={15} /> Remove</button>}</header><div className="admin-form-grid"><label className="admin-field">Starts <span>*</span><input type="datetime-local" value={item.starts_at} onChange={(e) => updateSession(index, { starts_at: e.target.value })} required /></label><label className="admin-field">Ends<input type="datetime-local" value={item.ends_at} onChange={(e) => updateSession(index, { ends_at: e.target.value })} /></label><label className="admin-field">Timezone<select value={item.timezone} onChange={(e) => updateSession(index, { timezone: e.target.value })}>{TIMEZONES.map((zone) => <option key={zone}>{zone}</option>)}</select></label><label className="admin-field">Capacity<input type="number" min="0" value={item.capacity} onChange={(e) => updateSession(index, { capacity: e.target.value })} /></label><label className="admin-field">Registration deadline<input type="datetime-local" value={item.registration_deadline} onChange={(e) => updateSession(index, { registration_deadline: e.target.value })} /></label><label className="admin-field">Registration status<select value={item.registration_status} onChange={(e) => updateSession(index, { registration_status: e.target.value as RegistrationStatus })}>{Object.entries(REGISTRATION_STATUS_LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="admin-field">Session status<select value={item.status} onChange={(e) => updateSession(index, { status: e.target.value as CourseStatus })}><option value="draft">Draft</option><option value="published" disabled={!can("courses.publish")}>Published</option><option value="archived">Archived</option></select></label><label className="admin-field">Sort order<input type="number" min="0" value={item.sort_order} onChange={(e) => updateSession(index, { sort_order: e.target.value })} /></label><label className="admin-field admin-field--wide">Session registration link<input type="url" value={item.registration_url} onChange={(e) => updateSession(index, { registration_url: e.target.value })} placeholder="Leave blank to use the course link" /></label></div></section>)}</div>}</fieldset>
      {formError && <p className="admin-error" role="alert">{formError}</p>}<footer><button type="button" className="admin-cancel" onClick={() => closeForm()} disabled={saving}>Cancel</button><button type="submit" className="button button-red" disabled={saving}>{saving ? "Saving…" : editing ? "Save changes" : "Add course"}</button></footer>
    </form></section></div>}
    {deleting && <div className="admin-modal-backdrop"><section className="admin-confirm" role="alertdialog" aria-modal="true"><div className="admin-confirm__icon"><Trash2 size={23} /></div><h2>Delete “{deleting.title}”?</h2><p>This permanently removes the course, all class sessions and its uploaded image. This action cannot be undone.</p><div><button type="button" className="admin-cancel" onClick={() => setDeleting(null)} disabled={deleteBusy}>Cancel</button><button type="button" className="admin-delete-confirm" onClick={confirmDelete} disabled={deleteBusy}>{deleteBusy ? "Deleting…" : "Delete course"}</button></div></section></div>}
  </main></div>;
}
