"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarDays, Clock3, Eye, ImagePlus, MapPin, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { getSupabaseBrowserClient } from "../../../lib/supabase/client";
import { useAdminPermissions } from "../../../lib/admin-access";
import { EVENT_MODE_LABELS, EVENT_STATUS_LABELS, EventMode, EventRecord, EventStatus, formatEventSchedule, getEventImageUrl, slugifyEventTitle } from "../../../lib/events";
import { AdminRole } from "../../../lib/news";
import AdminSidebar from "../AdminSidebar";

type EventFilter = "all" | "upcoming" | "past" | EventStatus;
type FormState = { title: string; slug: string; summary: string; description: string; starts_at: string; ends_at: string; timezone: string; is_all_day: boolean; mode: EventMode; location: string; registration_url: string; status: EventStatus; published_at: string };
const EVENT_SELECT = "id, slug, title, summary, description, cover_image_path, starts_at, ends_at, timezone, is_all_day, mode, location, registration_url, status, published_at, created_at, updated_at";
const FILTERS: Array<{ value: EventFilter; label: string }> = [{ value: "all", label: "All events" }, { value: "upcoming", label: "Upcoming" }, { value: "past", label: "Past" }, { value: "draft", label: "Draft" }, { value: "published", label: "Published" }, { value: "archived", label: "Archived" }];
const TIMEZONES = ["Asia/Bangkok", "Asia/Singapore", "Asia/Ho_Chi_Minh", "Asia/Yangon", "Asia/Dhaka", "Asia/Kuala_Lumpur", "UTC"];
const emptyForm = (): FormState => ({ title: "", slug: "", summary: "", description: "", starts_at: "", ends_at: "", timezone: "Asia/Bangkok", is_all_day: false, mode: "onsite", location: "", registration_url: "", status: "draft", published_at: "" });
const optional = (value: string) => value.trim() || null;
const safeFilename = (filename: string) => filename.toLowerCase().replace(/[^a-z0-9.]+/g, "-").replace(/^-+|-+$/g, "") || "event-cover";
function toLocal(value: string | null) { if (!value) return ""; const date = new Date(value); if (Number.isNaN(date.getTime())) return ""; return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export default function AdminEventsPage() {
  const { can } = useAdminPermissions();
  const [now] = useState(() => Date.now());
  const [role, setRole] = useState<AdminRole | null>(null); const [userLabel, setUserLabel] = useState("Administrator");
  const [events, setEvents] = useState<EventRecord[]>([]); const [filter, setFilter] = useState<EventFilter>("all"); const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [notice, setNotice] = useState("");
  const [editing, setEditing] = useState<EventRecord | null>(null); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState<FormState>(emptyForm()); const [slugTouched, setSlugTouched] = useState(false);
  const [coverFile, setCoverFile] = useState<File | null>(null); const [coverPreview, setCoverPreview] = useState<string | null>(null); const [formError, setFormError] = useState(""); const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState<EventRecord | null>(null); const [deleteBusy, setDeleteBusy] = useState(false);

  async function loadEvents() { setLoadError(""); const { data, error } = await getSupabaseBrowserClient().from("events").select(EVENT_SELECT).order("starts_at", { ascending: true }); if (error) { setEvents([]); setLoadError("We could not load the events. Please refresh and try again."); return; } setEvents((data ?? []) as EventRecord[]); }
  useEffect(() => { let active = true; (async () => { const supabase = getSupabaseBrowserClient(); const { data } = await supabase.auth.getUser(); if (!active) return; if (!data.user) { window.location.replace("/admin"); return; } const { data: profile } = await supabase.from("admin_profiles").select("email, display_name, role").eq("id", data.user.id).eq("is_active", true).maybeSingle(); if (!active) return; if (!profile) { await supabase.auth.signOut(); window.location.replace("/admin"); return; } setRole(profile.role as AdminRole); setUserLabel(profile.display_name ?? profile.email); await loadEvents(); if (active) setLoading(false); })(); return () => { active = false; }; }, []);
  useEffect(() => () => { if (coverPreview?.startsWith("blob:")) URL.revokeObjectURL(coverPreview); }, [coverPreview]);

  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return events.filter((item) => { const end = new Date(item.ends_at ?? item.starts_at).getTime(); const matchesFilter = filter === "all" || (filter === "upcoming" ? end >= now : filter === "past" ? end < now : item.status === filter); return matchesFilter && (!term || `${item.title} ${item.location ?? ""} ${item.mode}`.toLowerCase().includes(term)); }); }, [events, filter, search, now]);
  function count(value: EventFilter) { if (value === "all") return events.length; if (value === "upcoming") return events.filter((item) => new Date(item.ends_at ?? item.starts_at).getTime() >= now).length; if (value === "past") return events.filter((item) => new Date(item.ends_at ?? item.starts_at).getTime() < now).length; return events.filter((item) => item.status === value).length; }
  function openCreate() { setEditing(null); setForm(emptyForm()); setSlugTouched(false); setCoverFile(null); setCoverPreview(null); setFormError(""); setFormOpen(true); }
  function openEdit(item: EventRecord) { setEditing(item); setForm({ title: item.title, slug: item.slug, summary: item.summary, description: item.description, starts_at: toLocal(item.starts_at), ends_at: toLocal(item.ends_at), timezone: item.timezone, is_all_day: item.is_all_day, mode: item.mode, location: item.location ?? "", registration_url: item.registration_url ?? "", status: item.status, published_at: toLocal(item.published_at) }); setSlugTouched(true); setCoverFile(null); setCoverPreview(getEventImageUrl(item.cover_image_path)); setFormError(""); setFormOpen(true); }
  function closeForm() { if (saving) return; setFormOpen(false); setEditing(null); setCoverFile(null); setCoverPreview(null); setFormError(""); }
  function handleCover(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; setFormError(""); if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) { setFormError("Cover image must be a JPEG, PNG or WebP image."); event.target.value = ""; return; } if (file.size > 10 * 1024 * 1024) { setFormError("Cover image must be smaller than 10 MB."); event.target.value = ""; return; } if (coverPreview?.startsWith("blob:")) URL.revokeObjectURL(coverPreview); setCoverFile(file); setCoverPreview(URL.createObjectURL(file)); }
  async function removeCover(path: string | null) { if (!path || path.startsWith("/") || /^https?:\/\//i.test(path)) return null; const { error } = await getSupabaseBrowserClient().storage.from("cms-images").remove([path]); return error; }

  async function submitEvent(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setFormError(""); setNotice(""); const slug = slugifyEventTitle(form.slug);
    if (!form.title.trim() || !slug || !form.summary.trim() || !form.description.trim() || !form.starts_at) { setFormError("Title, URL slug, summary, description and start date are required."); return; }
    if (form.ends_at && new Date(form.ends_at) < new Date(form.starts_at)) { setFormError("End date must be after the start date."); return; }
    if (form.registration_url) { try { new URL(form.registration_url); } catch { setFormError("Registration link must be a complete URL, such as https://example.com/register."); return; } }
    if (form.status === "published" && !can("events.publish")) { setFormError("You do not have permission to publish an event. Save it as Draft for review."); return; }
    setSaving(true); const supabase = getSupabaseBrowserClient(); const { data: auth } = await supabase.auth.getUser(); const userId = auth.user?.id; if (!userId) { window.location.replace("/admin"); return; }
    const eventId = editing?.id ?? crypto.randomUUID(); let coverPath = editing?.cover_image_path ?? null; let uploadedPath: string | null = null;
    if (coverFile) { uploadedPath = `events/${eventId}/${Date.now()}-${safeFilename(coverFile.name)}`; const { error } = await supabase.storage.from("cms-images").upload(uploadedPath, coverFile, { contentType: coverFile.type, upsert: false }); if (error) { setFormError(`Cover upload failed: ${error.message}`); setSaving(false); return; } coverPath = uploadedPath; }
    const publishedAt = form.status === "published" ? (form.published_at ? new Date(form.published_at).toISOString() : editing?.published_at ?? new Date().toISOString()) : null;
    const values = { slug, title: form.title.trim(), summary: form.summary.trim(), description: form.description.trim(), cover_image_path: coverPath, starts_at: new Date(form.starts_at).toISOString(), ends_at: form.ends_at ? new Date(form.ends_at).toISOString() : null, timezone: form.timezone, is_all_day: form.is_all_day, mode: form.mode, location: optional(form.location), registration_url: optional(form.registration_url), status: form.status, published_at: publishedAt, updated_by: userId };
    const result = editing ? await supabase.from("events").update(values).eq("id", eventId) : await supabase.from("events").insert({ id: eventId, ...values, created_by: userId });
    if (result.error) { if (uploadedPath) await removeCover(uploadedPath); setFormError(`Event could not be saved: ${result.error.code === "23505" ? "This URL slug is already in use." : result.error.message}`); setSaving(false); return; }
    let cleanupFailed = false; if (can("events.delete") && uploadedPath && editing?.cover_image_path && editing.cover_image_path !== uploadedPath) cleanupFailed = Boolean(await removeCover(editing.cover_image_path));
    await loadEvents(); closeForm(); setNotice(`${form.title.trim()} was ${editing ? "updated" : "created"} successfully.${cleanupFailed ? " The previous cover could not be removed." : ""}`); setSaving(false);
  }

  async function confirmDelete() { if (!deleting || !can("events.delete")) return; setDeleteBusy(true); const supabase = getSupabaseBrowserClient(); const { error } = await supabase.from("events").delete().eq("id", deleting.id); if (error) { setLoadError(`Delete failed: ${error.message}`); setDeleteBusy(false); return; } const imageError = await removeCover(deleting.cover_image_path); setEvents((items) => items.filter((item) => item.id !== deleting.id)); setNotice(`${deleting.title} was deleted.${imageError ? " The cover could not be removed." : ""}`); setDeleting(null); setDeleteBusy(false); }
  async function signOut() { await getSupabaseBrowserClient().auth.signOut(); window.location.replace("/admin"); }
  if (loading || !role) return <main className="admin-dashboard admin-people"><div className="admin-loading" role="status">Checking access and loading events…</div></main>;

  return <div className="admin-workspace"><AdminSidebar active="events" userLabel={userLabel} role={role} onSignOut={signOut} /><main className="admin-dashboard admin-people admin-news admin-events">
    <header className="admin-people__header"><div><Link className="admin-back" href="/admin"><ArrowLeft size={17} /> Administration</Link><p className="admin-kicker">AACI CONTENT MANAGEMENT</p><h1>Events Management</h1><p>Create, schedule and publish events with external registration links.</p></div>{can("events.create") && <button className="button button-red admin-add-person" type="button" onClick={openCreate}><Plus size={18} /> Add event</button>}</header>
    <div className="admin-news__controls"><nav className="admin-people__tabs admin-events__tabs" aria-label="Event filters">{FILTERS.map((item) => <button key={item.value} type="button" aria-current={filter === item.value ? "page" : undefined} onClick={() => setFilter(item.value)}>{item.label}<span>{count(item.value)}</span></button>)}</nav><label className="admin-news__search"><Search size={17} /><span className="sr-only">Search events</span><input type="search" placeholder="Search events" value={search} onChange={(e) => setSearch(e.target.value)} /></label></div>
    {notice && <div className="admin-notice" role="status">{notice}<button type="button" aria-label="Dismiss notification" onClick={() => setNotice("")}><X size={16} /></button></div>}{loadError && <div className="admin-error admin-people__error" role="alert">{loadError}<button type="button" onClick={loadEvents}>Try again</button></div>}
    <section className="admin-people__list"><div className="admin-people__list-header"><div><h2>{FILTERS.find((item) => item.value === filter)?.label}</h2><p>{filtered.length} {filtered.length === 1 ? "event" : "events"}</p></div><small>Only published events appear on the public website.</small></div>{filtered.length === 0 ? <div className="admin-people__empty"><CalendarDays size={34} strokeWidth={1.5} /><h3>No events found</h3><p>Create an event or try a different filter.</p>{can("events.create") && <button className="button button-red" type="button" onClick={openCreate}><Plus size={17} /> Add event</button>}</div> : <div className="admin-news__rows">{filtered.map((item) => { const image = getEventImageUrl(item.cover_image_path); return <article className="admin-news-row admin-event-row" key={item.id}><div className="admin-news-row__image">{image ? <img src={image} alt="" /> : <CalendarDays size={25} strokeWidth={1.5} />}</div><div className="admin-news-row__identity"><p>{EVENT_MODE_LABELS[item.mode]}</p><h3>{item.title}</h3><small>{formatEventSchedule(item)}{item.location ? ` · ${item.location}` : ""}</small></div><span className={`admin-status admin-status--${item.status}`}>{EVENT_STATUS_LABELS[item.status]}</span><div className="admin-person-row__actions">{item.status === "published" && <Link href={`/events/${item.slug}`} target="_blank"><Eye size={16} /> View</Link>}{can("events.update") && <button type="button" onClick={() => openEdit(item)}><Pencil size={16} /> Edit</button>}{can("events.delete") && <button className="admin-person-row__delete" type="button" onClick={() => setDeleting(item)}><Trash2 size={16} /> Delete</button>}</div></article>; })}</div>}</section>
    {formOpen && <div className="admin-modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) closeForm(); }}><section className="admin-person-form admin-news-form" role="dialog" aria-modal="true" aria-labelledby="event-form-title"><header><div><p className="admin-kicker">{editing ? "EDIT EVENT" : "ADD EVENT"}</p><h2 id="event-form-title">{editing ? editing.title : "Create an event"}</h2></div><button type="button" onClick={closeForm} aria-label="Close form"><X size={22} /></button></header><form onSubmit={submitEvent}>
      <fieldset><legend>Event details</legend><div className="admin-form-grid"><label className="admin-field admin-field--wide">Title <span>*</span><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value, slug: slugTouched ? form.slug : slugifyEventTitle(e.target.value) })} required /></label><label className="admin-field">URL slug <span>*</span><input value={form.slug} onChange={(e) => { setSlugTouched(true); setForm({ ...form, slug: e.target.value }); }} required /></label><label className="admin-field">Format <span>*</span><select value={form.mode} onChange={(e) => setForm({ ...form, mode: e.target.value as EventMode })}>{Object.entries(EVENT_MODE_LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="admin-field admin-field--wide">Summary <span>*</span><textarea rows={3} value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} required /></label><label className="admin-field admin-field--wide">Description <span>*</span><textarea className="admin-news-form__content" rows={10} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} required /><small>Separate paragraphs with a blank line.</small></label><label className="admin-photo-field"><span>Cover image</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={handleCover} /><span className="admin-photo-picker admin-news-photo-picker">{coverPreview ? <img src={coverPreview} alt="Cover preview" /> : <ImagePlus size={25} />}<span><strong>{coverFile ? coverFile.name : "Choose an image"}</strong><small>JPEG, PNG or WebP · maximum 10 MB</small></span></span></label></div></fieldset>
      <fieldset><legend>Schedule and registration</legend><div className="admin-form-grid"><label className="admin-field">Starts <span>*</span><div className="admin-news-date"><CalendarDays size={16} /><input type="datetime-local" value={form.starts_at} onChange={(e) => setForm({ ...form, starts_at: e.target.value })} required /></div></label><label className="admin-field">Ends<div className="admin-news-date"><Clock3 size={16} /><input type="datetime-local" value={form.ends_at} onChange={(e) => setForm({ ...form, ends_at: e.target.value })} /></div></label><label className="admin-field admin-field--wide"><span className="admin-event-all-day"><input type="checkbox" checked={form.is_all_day} onChange={(e) => setForm({ ...form, is_all_day: e.target.checked })} /> All-day event <small>Hide times and show only the event date range.</small></span></label><label className="admin-field">Timezone<select value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })}>{TIMEZONES.map((zone) => <option key={zone}>{zone}</option>)}</select></label><label className="admin-field">Location<div className="admin-news-date"><MapPin size={16} /><input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} placeholder={form.mode === "online" ? "Zoom / online" : "Venue and city"} /></div></label><label className="admin-field admin-field--wide">External registration link<input type="url" value={form.registration_url} onChange={(e) => setForm({ ...form, registration_url: e.target.value })} placeholder="https://example.com/register" /><small>The public Register button opens this link in a new tab.</small></label></div></fieldset>
      <fieldset><legend>Publishing</legend><div className="admin-form-grid"><label className="admin-field">Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as EventStatus })}><option value="draft">Draft</option><option value="published" disabled={!can("events.publish")}>Published</option><option value="archived">Archived</option></select>{!can("events.publish") && <small>A role with Publish permission must publish events.</small>}</label><label className="admin-field">Publish date<div className="admin-news-date"><CalendarDays size={16} /><input type="datetime-local" value={form.published_at} onChange={(e) => setForm({ ...form, published_at: e.target.value })} /></div></label></div></fieldset>
      {formError && <p className="admin-error" role="alert">{formError}</p>}<footer><button type="button" className="admin-cancel" onClick={closeForm} disabled={saving}>Cancel</button><button type="submit" className="button button-red" disabled={saving}>{saving ? "Saving…" : editing ? "Save changes" : "Add event"}</button></footer>
    </form></section></div>}
    {deleting && <div className="admin-modal-backdrop"><section className="admin-confirm" role="alertdialog" aria-modal="true"><div className="admin-confirm__icon"><Trash2 size={23} /></div><h2>Delete “{deleting.title}”?</h2><p>This permanently removes the event and its cover image. This action cannot be undone.</p><div><button type="button" className="admin-cancel" onClick={() => setDeleting(null)} disabled={deleteBusy}>Cancel</button><button type="button" className="admin-delete-confirm" onClick={confirmDelete} disabled={deleteBusy}>{deleteBusy ? "Deleting…" : "Delete event"}</button></div></section></div>}
  </main></div>;
}
