"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Award, Building2, Eye, ImagePlus, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { getSupabaseBrowserClient } from "../../../lib/supabase/client";
import { useAdminPermissions } from "../../../lib/admin-access";
import { AdminRole } from "../../../lib/news";
import { ACCREDITATION_STATUS_LABELS, AccreditedOrganizationRecord, AccreditationStatus, getOrganizationLogoUrl, ORGANIZATION_STATUS_LABELS, OrganizationStatus, slugifyOrganization } from "../../../lib/organizations";
import AdminSidebar from "../AdminSidebar";

type DirectoryFilter = "all" | OrganizationStatus;
type OrganizationForm = {
  organization_name: string; slug: string; organization_type: string; programme: string;
  country_code: string; country_name: string; city: string; address: string;
  certificate_number: string; accreditation_scope: string; summary: string;
  issued_at: string; expires_at: string; accreditation_status: AccreditationStatus;
  website_url: string; status: OrganizationStatus; published_at: string; sort_order: string;
};

const ORGANIZATION_SELECT = "id, slug, organization_name, country_code, country_name, city, address, organization_type, programme, certificate_number, accreditation_scope, summary, issued_at, expires_at, accreditation_status, logo_path, website_url, status, published_at, sort_order, created_at, updated_at";
const FILTERS: Array<{ value: DirectoryFilter; label: string }> = [
  { value: "all", label: "All organizations" }, { value: "draft", label: "Draft" },
  { value: "published", label: "Published" }, { value: "archived", label: "Archived" },
];
const PROGRAMME_OPTIONS = ["AACI Accreditation", "Dental Accreditation", "ISO 9001:2015", "ISO 7101:2023", "CEC Acute Stroke", "CEC Endoscopy", "CEC Maternity", "CEC Oncology"];
const parseProgrammes = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean).map((item) => item === "AACI Healthcare Accreditation" ? "AACI Accreditation" : item);
const emptyForm = (): OrganizationForm => ({ organization_name: "", slug: "", organization_type: "Hospital", programme: "AACI Accreditation", country_code: "TH", country_name: "Thailand", city: "", address: "", certificate_number: "", accreditation_scope: "", summary: "", issued_at: "", expires_at: "", accreditation_status: "active", website_url: "", status: "draft", published_at: "", sort_order: "1" });
const optional = (value: string) => value.trim() || null;
const safeFilename = (filename: string) => filename.toLowerCase().replace(/[^a-z0-9.]+/g, "-").replace(/^-+|-+$/g, "") || "organization-logo";
function toLocal(value: string | null) { if (!value) return ""; const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export default function AdminOrganizationsPage() {
  const { can } = useAdminPermissions();
  const [role, setRole] = useState<AdminRole | null>(null); const [userLabel, setUserLabel] = useState("Administrator");
  const [organizations, setOrganizations] = useState<AccreditedOrganizationRecord[]>([]); const [filter, setFilter] = useState<DirectoryFilter>("all"); const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [notice, setNotice] = useState("");
  const [editing, setEditing] = useState<AccreditedOrganizationRecord | null>(null); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState<OrganizationForm>(emptyForm()); const [slugTouched, setSlugTouched] = useState(false);
  const [logoFile, setLogoFile] = useState<File | null>(null); const [logoPreview, setLogoPreview] = useState<string | null>(null); const [formError, setFormError] = useState(""); const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState<AccreditedOrganizationRecord | null>(null); const [deleteBusy, setDeleteBusy] = useState(false);

  async function loadOrganizations() {
    setLoadError(""); const { data, error } = await getSupabaseBrowserClient().from("accredited_organizations").select(ORGANIZATION_SELECT).order("sort_order", { ascending: true }).order("organization_name", { ascending: true });
    if (error) { setOrganizations([]); setLoadError("We could not load the directory. Run the latest Supabase migration, then refresh this page."); return; }
    setOrganizations((data ?? []) as AccreditedOrganizationRecord[]);
  }

  useEffect(() => { let active = true; (async () => { const supabase = getSupabaseBrowserClient(); const { data } = await supabase.auth.getUser(); if (!active) return; if (!data.user) { window.location.replace("/admin"); return; } const { data: profile } = await supabase.from("admin_profiles").select("email, display_name, role").eq("id", data.user.id).eq("is_active", true).maybeSingle(); if (!active) return; if (!profile) { await supabase.auth.signOut(); window.location.replace("/admin"); return; } setRole(profile.role as AdminRole); setUserLabel(profile.display_name ?? profile.email); await loadOrganizations(); if (active) setLoading(false); })(); return () => { active = false; }; }, []);
  useEffect(() => () => { if (logoPreview?.startsWith("blob:")) URL.revokeObjectURL(logoPreview); }, [logoPreview]);

  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return organizations.filter((item) => (filter === "all" || item.status === filter) && (!term || `${item.organization_name} ${item.country_name} ${item.city ?? ""} ${item.programme} ${item.certificate_number ?? ""}`.toLowerCase().includes(term))); }, [organizations, filter, search]);
  function count(value: DirectoryFilter) { return value === "all" ? organizations.length : organizations.filter((item) => item.status === value).length; }
  function updateName(value: string) { setForm((current) => ({ ...current, organization_name: value, slug: slugTouched ? current.slug : slugifyOrganization(value) })); }
  function toggleProgramme(programme: string) { setForm((current) => { const selected = parseProgrammes(current.programme); const next = selected.includes(programme) ? selected.filter((item) => item !== programme) : [...selected, programme]; return { ...current, programme: next.join(", ") }; }); }
  function openCreate() { setEditing(null); setForm({ ...emptyForm(), sort_order: String(organizations.length + 1) }); setSlugTouched(false); setLogoFile(null); setLogoPreview(null); setFormError(""); setFormOpen(true); }
  function openEdit(item: AccreditedOrganizationRecord) { setEditing(item); setForm({ organization_name: item.organization_name, slug: item.slug, organization_type: item.organization_type ?? "", programme: item.programme, country_code: item.country_code, country_name: item.country_name, city: item.city ?? "", address: item.address ?? "", certificate_number: item.certificate_number ?? "", accreditation_scope: item.accreditation_scope ?? "", summary: item.summary, issued_at: item.issued_at ?? "", expires_at: item.expires_at ?? "", accreditation_status: item.accreditation_status, website_url: item.website_url ?? "", status: item.status, published_at: toLocal(item.published_at), sort_order: String(item.sort_order) }); setSlugTouched(true); setLogoFile(null); setLogoPreview(getOrganizationLogoUrl(item.logo_path)); setFormError(""); setFormOpen(true); }
  function closeForm(force = false) { if (saving && !force) return; setFormOpen(false); setEditing(null); setLogoFile(null); setLogoPreview(null); setFormError(""); }
  function handleLogo(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type)) { setFormError("Logo must be a JPEG, PNG or WebP file."); event.target.value = ""; return; } if (file.size > 10 * 1024 * 1024) { setFormError("Logo must be no larger than 10 MB."); event.target.value = ""; return; } if (logoPreview?.startsWith("blob:")) URL.revokeObjectURL(logoPreview); setLogoFile(file); setLogoPreview(URL.createObjectURL(file)); setFormError(""); }
  async function removeLogo(path: string | null) { if (!path || path.startsWith("/") || /^https?:\/\//i.test(path)) return null; const { error } = await getSupabaseBrowserClient().storage.from("cms-images").remove([path]); return error; }

  async function submitOrganization(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setFormError("");
    if (!form.organization_name.trim() || !form.slug.trim() || !form.country_name.trim() || !form.country_code.trim() || !form.programme.trim()) { setFormError("Organization name, URL slug, country and programme are required."); setSaving(false); return; }
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(form.slug)) { setFormError("URL slug may contain lowercase letters, numbers and hyphens only."); setSaving(false); return; }
    if (!/^[A-Za-z]{2}$/.test(form.country_code.trim())) { setFormError("Country code must contain exactly two letters, for example TH."); setSaving(false); return; }
    if (form.issued_at && form.expires_at && form.expires_at < form.issued_at) { setFormError("Expiry date must be after the issue date."); setSaving(false); return; }
    const supabase = getSupabaseBrowserClient(); const { data: auth } = await supabase.auth.getUser(); const userId = auth.user?.id; if (!userId) { window.location.replace("/admin"); return; }
    const organizationId = editing?.id ?? crypto.randomUUID(); let logoPath = editing?.logo_path ?? null; let uploadedPath: string | null = null;
    if (logoFile) { uploadedPath = `organizations/${organizationId}/${Date.now()}-${safeFilename(logoFile.name)}`; const { error } = await supabase.storage.from("cms-images").upload(uploadedPath, logoFile, { contentType: logoFile.type, upsert: false }); if (error) { setFormError(`Logo upload failed: ${error.message}`); setSaving(false); return; } logoPath = uploadedPath; }
    const values = { slug: form.slug.trim(), organization_name: form.organization_name.trim(), country_code: form.country_code.trim().toUpperCase(), country_name: form.country_name.trim(), city: optional(form.city), address: optional(form.address), organization_type: optional(form.organization_type), programme: form.programme.trim(), certificate_number: optional(form.certificate_number), accreditation_scope: optional(form.accreditation_scope), summary: form.summary.trim(), issued_at: optional(form.issued_at), expires_at: optional(form.expires_at), accreditation_status: form.accreditation_status, logo_path: logoPath, website_url: optional(form.website_url), status: form.status, published_at: form.status === "published" ? (form.published_at ? new Date(form.published_at).toISOString() : editing?.published_at ?? new Date().toISOString()) : (form.published_at ? new Date(form.published_at).toISOString() : null), sort_order: Math.max(0, Number(form.sort_order) || 0), updated_by: userId };
    const result = editing ? await supabase.from("accredited_organizations").update(values).eq("id", organizationId) : await supabase.from("accredited_organizations").insert({ id: organizationId, ...values, created_by: userId });
    if (result.error) { if (uploadedPath) await removeLogo(uploadedPath); setFormError(`Organization could not be saved: ${result.error.code === "23505" ? "The URL slug or certificate number is already in use." : result.error.message}`); setSaving(false); return; }
    let cleanupFailed = false; if (can("organizations.delete") && uploadedPath && editing?.logo_path && editing.logo_path !== uploadedPath) cleanupFailed = Boolean(await removeLogo(editing.logo_path));
    await loadOrganizations(); closeForm(true); setNotice(`${form.organization_name.trim()} was ${editing ? "updated" : "created"} successfully.${cleanupFailed ? " The previous logo could not be removed." : ""}`); setSaving(false);
  }

  async function confirmDelete() { if (!deleting || !can("organizations.delete")) return; setDeleteBusy(true); const supabase = getSupabaseBrowserClient(); const { error } = await supabase.from("accredited_organizations").delete().eq("id", deleting.id); if (error) { setLoadError(`Delete failed: ${error.message}`); setDeleteBusy(false); return; } const logoError = await removeLogo(deleting.logo_path); setOrganizations((items) => items.filter((item) => item.id !== deleting.id)); setNotice(`${deleting.organization_name} was deleted.${logoError ? " The logo could not be removed." : ""}`); setDeleting(null); setDeleteBusy(false); }
  async function signOut() { await getSupabaseBrowserClient().auth.signOut(); window.location.replace("/admin"); }
  if (loading || !role) return <main className="admin-dashboard admin-people"><div className="admin-loading" role="status">Checking access and loading organizations…</div></main>;

  return <div className="admin-workspace"><AdminSidebar active="organizations" userLabel={userLabel} role={role} onSignOut={signOut} /><main className="admin-dashboard admin-people admin-news admin-organizations">
    <header className="admin-people__header"><div><Link className="admin-back" href="/admin"><ArrowLeft size={17} /> Administration</Link><p className="admin-kicker">AACI CONTENT MANAGEMENT</p><h1>Accredited Organizations</h1><p>Maintain verified public accreditation records and certificate details.</p></div>{can("organizations.create") && <button className="button button-red admin-add-person" type="button" onClick={openCreate}><Plus size={18} /> Add organization</button>}</header>
    <div className="admin-news__controls"><nav className="admin-people__tabs" aria-label="Organization filters">{FILTERS.map((item) => <button key={item.value} type="button" aria-current={filter === item.value ? "page" : undefined} onClick={() => setFilter(item.value)}>{item.label}<span>{count(item.value)}</span></button>)}</nav><label className="admin-news__search"><Search size={17} /><span className="sr-only">Search organizations</span><input type="search" placeholder="Search organizations" value={search} onChange={(event) => setSearch(event.target.value)} /></label></div>
    {notice && <div className="admin-notice" role="status">{notice}<button type="button" aria-label="Dismiss notification" onClick={() => setNotice("")}><X size={16} /></button></div>}{loadError && <div className="admin-error admin-people__error" role="alert">{loadError}<button type="button" onClick={loadOrganizations}>Try again</button></div>}
    <section className="admin-people__list"><div className="admin-people__list-header"><div><h2>{FILTERS.find((item) => item.value === filter)?.label}</h2><p>{filtered.length} {filtered.length === 1 ? "organization" : "organizations"}</p></div><small>Only published records appear in the public directory.</small></div>{filtered.length === 0 ? <div className="admin-people__empty"><Award size={34} strokeWidth={1.5} /><h3>No organizations found</h3><p>Add an organization or try a different filter.</p>{can("organizations.create") && <button className="button button-red" type="button" onClick={openCreate}><Plus size={17} /> Add organization</button>}</div> : <div className="admin-news__rows">{filtered.map((item) => { const logo = getOrganizationLogoUrl(item.logo_path); return <article className="admin-news-row admin-organization-row" key={item.id}><div className="admin-news-row__image">{logo ? <img src={logo} alt="" /> : <Building2 size={28} strokeWidth={1.5} />}</div><div className="admin-news-row__identity"><p>{item.programme}</p><h3>{item.organization_name}</h3><small>{item.city ? `${item.city}, ` : ""}{item.country_name} · {item.certificate_number || "No certificate number"} · {ACCREDITATION_STATUS_LABELS[item.accreditation_status]}</small></div><span className={`admin-status admin-status--${item.status}`}>{ORGANIZATION_STATUS_LABELS[item.status]}</span><div className="admin-person-row__actions">{item.status === "published" && <Link href="/accredited-organizations" target="_blank"><Eye size={16} /> View</Link>}{can("organizations.update") && <button type="button" onClick={() => openEdit(item)}><Pencil size={16} /> Edit</button>}{can("organizations.delete") && <button className="admin-person-row__delete" type="button" onClick={() => setDeleting(item)}><Trash2 size={16} /> Delete</button>}</div></article>; })}</div>}</section>
  </main>{formOpen && <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) closeForm(); }}><section className="admin-person-form admin-course-form" role="dialog" aria-modal="true" aria-labelledby="organization-form-title"><header><div><p className="admin-kicker">ACCREDITATION DIRECTORY</p><h2 id="organization-form-title">{editing ? "Edit organization" : "Add organization"}</h2></div><button type="button" aria-label="Close form" onClick={() => closeForm()}><X size={22} /></button></header><form onSubmit={submitOrganization}>
    <fieldset><legend>Organization</legend><div className="admin-form-grid"><label className="admin-field admin-field--wide">Organization name <span>*</span><input value={form.organization_name} onChange={(event) => updateName(event.target.value)} required /></label><label className="admin-field admin-field--wide">URL slug <span>*</span><input value={form.slug} onChange={(event) => { setSlugTouched(true); setForm({ ...form, slug: event.target.value.toLowerCase() }); }} required /></label><label className="admin-field">Organization type<input value={form.organization_type} onChange={(event) => setForm({ ...form, organization_type: event.target.value })} placeholder="Hospital" /></label><div className="admin-field admin-field--wide"><div className="admin-programme-label">Programme <span>*</span></div><div className="admin-programme-options" role="group" aria-label="Accreditation programmes">{PROGRAMME_OPTIONS.map((programme) => <label key={programme}><input type="checkbox" checked={parseProgrammes(form.programme).includes(programme)} onChange={() => toggleProgramme(programme)} /><span>{programme}</span></label>)}</div></div></div></fieldset>
    <fieldset><legend>Accreditation</legend><div className="admin-form-grid"><label className="admin-field">Certificate number<input value={form.certificate_number} onChange={(event) => setForm({ ...form, certificate_number: event.target.value })} /></label><label className="admin-field">Accreditation status<select value={form.accreditation_status} onChange={(event) => setForm({ ...form, accreditation_status: event.target.value as AccreditationStatus })}>{Object.entries(ACCREDITATION_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div></fieldset>
    <fieldset><legend>Logo</legend><div className="admin-image-upload"><div>{logoPreview ? <img src={logoPreview} alt="Organization logo preview" /> : <ImagePlus size={34} strokeWidth={1.4} />}</div><label><strong>{logoPreview ? "Replace logo" : "Upload logo"}</strong><span>JPEG, PNG or WebP · Maximum 10 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={handleLogo} /></label></div></fieldset>
    <fieldset><legend>Publishing</legend><div className="admin-form-grid"><label className="admin-field">Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as OrganizationStatus })}><option value="draft">Draft</option><option value="published" disabled={!can("organizations.publish")}>Published</option><option value="archived">Archived</option></select>{!can("organizations.publish") && <small>A role with Publish permission must publish organizations.</small>}</label><label className="admin-field">Publish date<input type="datetime-local" value={form.published_at} onChange={(event) => setForm({ ...form, published_at: event.target.value })} /></label><label className="admin-field">Sort order<input type="number" min="0" value={form.sort_order} onChange={(event) => setForm({ ...form, sort_order: event.target.value })} /></label></div></fieldset>
    {formError && <p className="admin-error admin-form-error" role="alert">{formError}</p>}<footer className="admin-form-actions"><button type="button" onClick={() => closeForm()} disabled={saving}>Cancel</button><button className="button button-red" type="submit" disabled={saving}>{saving ? "Saving…" : editing ? "Save changes" : "Create organization"}</button></footer>
  </form></section></div>}{deleting && <div className="admin-modal-backdrop"><section className="admin-delete-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-organization-title"><Trash2 size={28} /><h2 id="delete-organization-title">Delete {deleting.organization_name}?</h2><p>This permanently removes the directory record and its uploaded logo.</p><div><button type="button" onClick={() => setDeleting(null)} disabled={deleteBusy}>Cancel</button><button type="button" onClick={confirmDelete} disabled={deleteBusy}>{deleteBusy ? "Deleting…" : "Delete organization"}</button></div></section></div>}</div>;
}
