create table public.roles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  description text not null default '',
  is_system boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.permissions (
  key text primary key check (key ~ '^[a-z0-9_]+\.[a-z0-9_]+$'),
  module text not null,
  action text not null,
  description text not null default '',
  sort_order integer not null default 0
);

create table public.role_permissions (
  role_id uuid not null references public.roles(id) on delete cascade,
  permission_key text not null references public.permissions(key) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (role_id, permission_key)
);

create table public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);
create index admin_audit_log_created_idx on public.admin_audit_log (created_at desc);

insert into public.roles (name, slug, description, is_system) values
  ('Super Admin', 'admin', 'Full access to content, users, roles and permissions.', true),
  ('Admin', 'content-admin', 'Manages content and users without changing access-control rules.', true),
  ('Editor', 'editor', 'Creates and edits content for administrator review.', true),
  ('Viewer', 'viewer', 'Read-only access to administration content.', true);

insert into public.permissions (key, module, action, description, sort_order) values
  ('dashboard.view', 'Dashboard', 'View', 'Open the administration dashboard.', 10),
  ('people.view', 'People', 'View', 'View people and assignments.', 100),
  ('people.create', 'People', 'Create', 'Create people and assignments.', 101),
  ('people.update', 'People', 'Update', 'Edit people and assignments.', 102),
  ('people.publish', 'People', 'Publish', 'Publish people and assignments.', 103),
  ('people.delete', 'People', 'Delete', 'Permanently delete people and assignments.', 104),
  ('news.view', 'News', 'View', 'View all news articles.', 200),
  ('news.create', 'News', 'Create', 'Create news articles.', 201),
  ('news.update', 'News', 'Update', 'Edit news articles.', 202),
  ('news.publish', 'News', 'Publish', 'Publish news articles.', 203),
  ('news.delete', 'News', 'Delete', 'Permanently delete news articles.', 204),
  ('events.view', 'Events', 'View', 'View all events.', 300),
  ('events.create', 'Events', 'Create', 'Create events.', 301),
  ('events.update', 'Events', 'Update', 'Edit events.', 302),
  ('events.publish', 'Events', 'Publish', 'Publish events.', 303),
  ('events.delete', 'Events', 'Delete', 'Permanently delete events.', 304),
  ('courses.view', 'Courses', 'View', 'View all courses and sessions.', 400),
  ('courses.create', 'Courses', 'Create', 'Create courses and sessions.', 401),
  ('courses.update', 'Courses', 'Update', 'Edit courses and sessions.', 402),
  ('courses.publish', 'Courses', 'Publish', 'Publish courses and sessions.', 403),
  ('courses.delete', 'Courses', 'Delete', 'Permanently delete courses and sessions.', 404),
  ('organizations.view', 'Organizations', 'View', 'View all accredited organizations.', 500),
  ('organizations.create', 'Organizations', 'Create', 'Create accredited organizations.', 501),
  ('organizations.update', 'Organizations', 'Update', 'Edit accredited organizations.', 502),
  ('organizations.publish', 'Organizations', 'Publish', 'Publish accredited organizations.', 503),
  ('organizations.delete', 'Organizations', 'Delete', 'Permanently delete accredited organizations.', 504),
  ('users.view', 'Users', 'View', 'View administration users.', 800),
  ('users.create', 'Users', 'Create', 'Invite administration users.', 801),
  ('users.update', 'Users', 'Update', 'Change user names and roles.', 802),
  ('users.disable', 'Users', 'Disable', 'Activate or disable administration users.', 803),
  ('roles.view', 'Roles', 'View', 'View roles and their permissions.', 900),
  ('roles.manage', 'Roles', 'Manage', 'Create roles and change role permissions.', 901);

insert into public.role_permissions (role_id, permission_key)
select r.id, p.key from public.roles r cross join public.permissions p where r.slug = 'admin';

insert into public.role_permissions (role_id, permission_key)
select r.id, p.key
from public.roles r cross join public.permissions p
where r.slug = 'content-admin' and p.key <> 'roles.manage';

insert into public.role_permissions (role_id, permission_key)
select r.id, p.key
from public.roles r cross join public.permissions p
where r.slug = 'editor'
  and (p.key = 'dashboard.view' or p.action in ('View', 'Create', 'Update'))
  and p.module not in ('Users', 'Roles');

insert into public.role_permissions (role_id, permission_key)
select r.id, p.key
from public.roles r cross join public.permissions p
where r.slug = 'viewer'
  and (p.key = 'dashboard.view' or p.action = 'View')
  and p.module not in ('Users', 'Roles');

alter table public.admin_profiles add column role_id uuid references public.roles(id) on delete restrict;
update public.admin_profiles ap set role_id = r.id from public.roles r where r.slug = ap.role;
alter table public.admin_profiles alter column role_id set not null;
alter table public.admin_profiles drop constraint if exists admin_profiles_role_check;

create or replace function public.sync_admin_profile_role()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  select slug into new.role from public.roles where id = new.role_id;
  if new.role is null then raise exception 'A valid role is required'; end if;
  return new;
end;
$$;

create trigger roles_set_updated_at before update on public.roles for each row execute function public.set_updated_at();
create trigger admin_profiles_sync_role before insert or update of role_id on public.admin_profiles for each row execute function public.sync_admin_profile_role();

create or replace function public.has_permission(requested_permission text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles ap
    join public.role_permissions rp on rp.role_id = ap.role_id
    where ap.id = auth.uid()
      and ap.is_active = true
      and rp.permission_key = requested_permission
  );
$$;

create or replace function public.get_my_permissions()
returns setof text
language sql
stable
security definer
set search_path = public
as $$
  select rp.permission_key
  from public.admin_profiles ap
  join public.role_permissions rp on rp.role_id = ap.role_id
  where ap.id = auth.uid() and ap.is_active = true
  order by rp.permission_key;
$$;

create or replace function public.is_cms_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_profiles where id = auth.uid() and is_active = true);
$$;

create or replace function public.is_cms_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.has_permission('roles.manage');
$$;

create or replace function public.admin_update_user(
  target_user_id uuid,
  new_display_name text,
  new_role_id uuid,
  new_is_active boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_role_slug text;
  current_role_slug text;
  active_super_admins integer;
begin
  if not public.has_permission('users.update') then raise exception 'Permission denied'; end if;
  if new_is_active = false and not public.has_permission('users.disable') then raise exception 'Permission denied'; end if;

  select r.slug into target_role_slug from public.roles r where r.id = new_role_id;
  if target_role_slug is null then raise exception 'Invalid role'; end if;
  if target_role_slug = 'admin' and not public.has_permission('roles.manage') then raise exception 'Only a Super Admin can assign the Super Admin role'; end if;

  select r.slug into current_role_slug
  from public.admin_profiles ap join public.roles r on r.id = ap.role_id
  where ap.id = target_user_id;
  if current_role_slug is null then raise exception 'User not found'; end if;
  if current_role_slug = 'admin' and not public.has_permission('roles.manage') then
    raise exception 'Only a Super Admin can change a Super Admin account';
  end if;

  if target_user_id = auth.uid() and (new_is_active = false or target_role_slug <> current_role_slug) then
    raise exception 'You cannot disable yourself or change your own role';
  end if;

  if current_role_slug = 'admin' and (target_role_slug <> 'admin' or new_is_active = false) then
    select count(*) into active_super_admins
    from public.admin_profiles ap join public.roles r on r.id = ap.role_id
    where r.slug = 'admin' and ap.is_active = true;
    if active_super_admins <= 1 then raise exception 'The last active Super Admin cannot be changed'; end if;
  end if;

  update public.admin_profiles
  set display_name = nullif(trim(new_display_name), ''), role_id = new_role_id, is_active = new_is_active
  where id = target_user_id;
  insert into public.admin_audit_log (actor_id, action, target_type, target_id, details)
  values (auth.uid(), 'user.updated', 'admin_user', target_user_id::text, jsonb_build_object('role_id', new_role_id, 'is_active', new_is_active));
end;
$$;

create or replace function public.admin_save_role(
  target_role_id uuid,
  new_name text,
  new_slug text,
  new_description text,
  permission_keys text[]
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  saved_role_id uuid;
  saved_role_slug text;
  saved_is_system boolean;
begin
  if not public.has_permission('roles.manage') then raise exception 'Permission denied'; end if;
  if nullif(trim(new_name), '') is null then raise exception 'Role name is required'; end if;
  if new_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' then raise exception 'Role slug is invalid'; end if;

  if target_role_id is null then
    insert into public.roles (name, slug, description)
    values (trim(new_name), new_slug, trim(coalesce(new_description, '')))
    returning id into saved_role_id;
  else
    select slug, is_system into saved_role_slug, saved_is_system from public.roles where id = target_role_id;
    if saved_role_slug is null then raise exception 'Role not found'; end if;
    if saved_role_slug = 'admin' then raise exception 'Super Admin permissions cannot be changed'; end if;
    saved_role_id := target_role_id;
    if not saved_is_system then
      update public.roles set name = trim(new_name), slug = new_slug, description = trim(coalesce(new_description, '')) where id = saved_role_id;
    end if;
  end if;

  delete from public.role_permissions where role_id = saved_role_id;
  insert into public.role_permissions (role_id, permission_key)
  select saved_role_id, p.key from public.permissions p where p.key = any(coalesce(permission_keys, array[]::text[]));
  insert into public.admin_audit_log (actor_id, action, target_type, target_id, details)
  values (auth.uid(), case when target_role_id is null then 'role.created' else 'role.updated' end, 'role', saved_role_id::text, jsonb_build_object('permission_count', cardinality(coalesce(permission_keys, array[]::text[]))));
  return saved_role_id;
end;
$$;

alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.admin_audit_log enable row level security;

create policy "CMS users can view roles" on public.roles for select to authenticated using (public.is_cms_user());
create policy "Authorized users can create roles" on public.roles for insert to authenticated with check (public.has_permission('roles.manage'));
create policy "Authorized users can update roles" on public.roles for update to authenticated using (public.has_permission('roles.manage')) with check (public.has_permission('roles.manage'));
create policy "Authorized users can delete custom roles" on public.roles for delete to authenticated using (public.has_permission('roles.manage') and not is_system);
create policy "CMS users can view permissions" on public.permissions for select to authenticated using (public.is_cms_user());
create policy "Authorized users can view role permissions" on public.role_permissions for select to authenticated using (public.has_permission('roles.view'));
create policy "Authorized users can create role permissions" on public.role_permissions for insert to authenticated with check (public.has_permission('roles.manage'));
create policy "Authorized users can delete role permissions" on public.role_permissions for delete to authenticated using (public.has_permission('roles.manage'));
create policy "Super Admins can view the access audit log" on public.admin_audit_log for select to authenticated using (public.has_permission('roles.manage'));

drop policy if exists "Users can view their own CMS profile" on public.admin_profiles;
drop policy if exists "Admins can create CMS profiles" on public.admin_profiles;
drop policy if exists "Admins can update CMS profiles" on public.admin_profiles;
drop policy if exists "Admins can delete CMS profiles" on public.admin_profiles;
create policy "Users can view permitted CMS profiles" on public.admin_profiles
for select to authenticated using (id = auth.uid() or public.has_permission('users.view'));

drop policy if exists "CMS users can view all news" on public.news;
drop policy if exists "CMS users can create news" on public.news;
drop policy if exists "CMS users can update news" on public.news;
drop policy if exists "Admins can delete news" on public.news;
create policy "Authorized users can view all news" on public.news for select to authenticated using (public.has_permission('news.view'));
create policy "Authorized users can create news" on public.news for insert to authenticated with check (public.has_permission('news.create') and (status <> 'published' or public.has_permission('news.publish')));
create policy "Authorized users can update news" on public.news for update to authenticated using (public.has_permission('news.update')) with check (public.has_permission('news.update') and (status <> 'published' or public.has_permission('news.publish')));
create policy "Authorized users can delete news" on public.news for delete to authenticated using (public.has_permission('news.delete'));

drop policy if exists "CMS users can view all events" on public.events;
drop policy if exists "CMS users can create events" on public.events;
drop policy if exists "CMS users can update events" on public.events;
drop policy if exists "Admins can delete events" on public.events;
create policy "Authorized users can view all events" on public.events for select to authenticated using (public.has_permission('events.view'));
create policy "Authorized users can create events" on public.events for insert to authenticated with check (public.has_permission('events.create') and (status <> 'published' or public.has_permission('events.publish')));
create policy "Authorized users can update events" on public.events for update to authenticated using (public.has_permission('events.update')) with check (public.has_permission('events.update') and (status <> 'published' or public.has_permission('events.publish')));
create policy "Authorized users can delete events" on public.events for delete to authenticated using (public.has_permission('events.delete'));

drop policy if exists "CMS users can view all courses" on public.courses;
drop policy if exists "CMS users can create courses" on public.courses;
drop policy if exists "CMS users can update courses" on public.courses;
drop policy if exists "Admins can delete courses" on public.courses;
create policy "Authorized users can view all courses" on public.courses for select to authenticated using (public.has_permission('courses.view'));
create policy "Authorized users can create courses" on public.courses for insert to authenticated with check (public.has_permission('courses.create') and (status <> 'published' or public.has_permission('courses.publish')));
create policy "Authorized users can update courses" on public.courses for update to authenticated using (public.has_permission('courses.update')) with check (public.has_permission('courses.update') and (status <> 'published' or public.has_permission('courses.publish')));
create policy "Authorized users can delete courses" on public.courses for delete to authenticated using (public.has_permission('courses.delete'));

drop policy if exists "CMS users can view all course sessions" on public.course_sessions;
drop policy if exists "CMS users can create course sessions" on public.course_sessions;
drop policy if exists "CMS users can update course sessions" on public.course_sessions;
drop policy if exists "Admins can delete course sessions" on public.course_sessions;
create policy "Authorized users can view all course sessions" on public.course_sessions for select to authenticated using (public.has_permission('courses.view'));
create policy "Authorized users can create course sessions" on public.course_sessions for insert to authenticated with check (public.has_permission('courses.create') and (status <> 'published' or public.has_permission('courses.publish')));
create policy "Authorized users can update course sessions" on public.course_sessions for update to authenticated using (public.has_permission('courses.update')) with check (public.has_permission('courses.update') and (status <> 'published' or public.has_permission('courses.publish')));
create policy "Authorized users can delete course sessions" on public.course_sessions for delete to authenticated using (public.has_permission('courses.delete'));

drop policy if exists "CMS users can view all organizations" on public.accredited_organizations;
drop policy if exists "CMS users can create organizations" on public.accredited_organizations;
drop policy if exists "CMS users can update organizations" on public.accredited_organizations;
drop policy if exists "Admins can delete organizations" on public.accredited_organizations;
create policy "Authorized users can view all organizations" on public.accredited_organizations for select to authenticated using (public.has_permission('organizations.view'));
create policy "Authorized users can create organizations" on public.accredited_organizations for insert to authenticated with check (public.has_permission('organizations.create') and (status <> 'published' or public.has_permission('organizations.publish')));
create policy "Authorized users can update organizations" on public.accredited_organizations for update to authenticated using (public.has_permission('organizations.update')) with check (public.has_permission('organizations.update') and (status <> 'published' or public.has_permission('organizations.publish')));
create policy "Authorized users can delete organizations" on public.accredited_organizations for delete to authenticated using (public.has_permission('organizations.delete'));

drop policy if exists "CMS users can view all people" on public.people;
drop policy if exists "CMS users can create people" on public.people;
drop policy if exists "CMS users can update people" on public.people;
drop policy if exists "Admins can delete people" on public.people;
create policy "Authorized users can view all people" on public.people for select to authenticated using (public.has_permission('people.view'));
create policy "Authorized users can create people" on public.people for insert to authenticated with check (public.has_permission('people.create') and (status <> 'published' or public.has_permission('people.publish')));
create policy "Authorized users can update people" on public.people for update to authenticated using (public.has_permission('people.update')) with check (public.has_permission('people.update') and (status <> 'published' or public.has_permission('people.publish')));
create policy "Authorized users can delete people" on public.people for delete to authenticated using (public.has_permission('people.delete'));

drop policy if exists "CMS users can view all assignments" on public.person_assignments;
drop policy if exists "CMS users can create assignments" on public.person_assignments;
drop policy if exists "CMS users can update assignments" on public.person_assignments;
drop policy if exists "Admins can delete assignments" on public.person_assignments;
create policy "Authorized users can view all assignments" on public.person_assignments for select to authenticated using (public.has_permission('people.view'));
create policy "Authorized users can create assignments" on public.person_assignments for insert to authenticated with check (public.has_permission('people.create') and (status <> 'published' or public.has_permission('people.publish')));
create policy "Authorized users can update assignments" on public.person_assignments for update to authenticated using (public.has_permission('people.update')) with check (public.has_permission('people.update') and (status <> 'published' or public.has_permission('people.publish')));
create policy "Authorized users can delete assignments" on public.person_assignments for delete to authenticated using (public.has_permission('people.delete'));

drop policy if exists "CMS users can view all assignment countries" on public.person_assignment_countries;
drop policy if exists "CMS users can create assignment countries" on public.person_assignment_countries;
drop policy if exists "CMS users can update assignment countries" on public.person_assignment_countries;
drop policy if exists "Admins can delete assignment countries" on public.person_assignment_countries;
create policy "Authorized users can view all assignment countries" on public.person_assignment_countries for select to authenticated using (public.has_permission('people.view'));
create policy "Authorized users can create assignment countries" on public.person_assignment_countries for insert to authenticated with check (public.has_permission('people.create'));
create policy "Authorized users can update assignment countries" on public.person_assignment_countries for update to authenticated using (public.has_permission('people.update')) with check (public.has_permission('people.update'));
create policy "Authorized users can delete assignment countries" on public.person_assignment_countries for delete to authenticated using (public.has_permission('people.delete'));

drop policy if exists "CMS users can upload CMS assets" on storage.objects;
drop policy if exists "CMS users can update CMS assets" on storage.objects;
drop policy if exists "Admins can delete CMS assets" on storage.objects;
create policy "Authorized users can upload CMS assets" on storage.objects for insert to authenticated
with check (bucket_id in ('cms-images', 'cms-files') and (
  ((storage.foldername(name))[1] = 'news' and public.has_permission('news.create')) or
  ((storage.foldername(name))[1] = 'events' and public.has_permission('events.create')) or
  ((storage.foldername(name))[1] = 'courses' and public.has_permission('courses.create')) or
  ((storage.foldername(name))[1] = 'organizations' and public.has_permission('organizations.create')) or
  ((storage.foldername(name))[1] = 'people' and public.has_permission('people.create'))
));
create policy "Authorized users can update CMS assets" on storage.objects for update to authenticated
using (bucket_id in ('cms-images', 'cms-files') and (
  ((storage.foldername(name))[1] = 'news' and public.has_permission('news.update')) or
  ((storage.foldername(name))[1] = 'events' and public.has_permission('events.update')) or
  ((storage.foldername(name))[1] = 'courses' and public.has_permission('courses.update')) or
  ((storage.foldername(name))[1] = 'organizations' and public.has_permission('organizations.update')) or
  ((storage.foldername(name))[1] = 'people' and public.has_permission('people.update'))
))
with check (bucket_id in ('cms-images', 'cms-files') and public.is_cms_user());
create policy "Authorized users can delete CMS assets" on storage.objects for delete to authenticated
using (bucket_id in ('cms-images', 'cms-files') and (
  ((storage.foldername(name))[1] = 'news' and public.has_permission('news.delete')) or
  ((storage.foldername(name))[1] = 'events' and public.has_permission('events.delete')) or
  ((storage.foldername(name))[1] = 'courses' and public.has_permission('courses.delete')) or
  ((storage.foldername(name))[1] = 'organizations' and public.has_permission('organizations.delete')) or
  ((storage.foldername(name))[1] = 'people' and public.has_permission('people.delete'))
));

grant select on public.roles, public.permissions, public.role_permissions, public.admin_audit_log to authenticated;
grant insert, update, delete on public.roles, public.role_permissions to authenticated;
grant execute on function public.has_permission(text), public.get_my_permissions(), public.admin_update_user(uuid, text, uuid, boolean), public.admin_save_role(uuid, text, text, text, text[]) to authenticated;
